export const ERROR_MESSAGE = {
  DOT_NOT_HAVE_PERMISSION: 'You do not have permission!',
  PROFILE_NOT_VALID: 'Your profile is not valid',
  CAN_NOT_START_TRIAL: 'This profile cannot apply for free trial',
  CLIENT_EXISTED_IN_PRACTITIONER: 'Cannot send invitation to existed client',
  PROFILE_STATUS_NOT_VALID: 'This profile is inactive',
  PROFILE_NOT_FOUND: 'This profile is not exist',
  EMAIL_NOT_VALID: 'This email is not valid',
  EMAIL_NOT_EXISTED: 'This email does not exist',
  OTP_NOT_VALID: 'This otp is not valid',
  EMAIL_REGISTERED: 'This email has been registered',
  PROFILE_IS_ACTIVE: 'This profile has been verified',
  CLIENT_INVITE_NOT_EXIST: 'Invite invalid',
  CLIENT_INVITE_STATUS_INVALID: 'This invite is status invalid',
  CLIENT_STATUS_INVALID: 'Client is not active',
  CLIENT_EXISTED: 'Client is existed',
  CLIENT_NOT_FOUND: 'Client not found',
  DISCHARGE_FAIL_BY_CLIENT_STATUS: 'Can not discharge due to client status error',
  HOMEWORK_STATUS_ERROR: 'Some homework is inactive. Please check it again',
  HOMEWORK_ASSIGN_NOT_FOUND: 'Homework assigned not found',
  DO_HOMEWORK_ASSIGN_DATE_ERROR: 'Cannot do this homework because it not available today',
  HOMEWORK_ASSIGN_STATUS_ERROR: 'Homework assigned is not active',
  HOMEWORK_ID_NOT_EXIST: "Homework doesn't exist",
  PRACTITIONER_ID_NOT_EXIT: "practitioner doesn't not exist",
  HOMEWORK_TOPIC_NOT_FOUND: 'The topic has been deleted by admin',
  HOMEWORK_TOPIC_RESTRICT_UPDATE: 'Do not have permission to change this homework topic!',
  HOMEWORK_TYPE_INVALID: 'Homework type is invalid',
  HOMEWORK_RESTRICT_UPDATE: 'Do not have permission to change this homework!',
  CARD_NOT_EXISTED: `Card doesn't exist`,
  PLAN_NOT_FOUND: 'Plan not found',
  SUBSCRIPTION_EXISTED: `Have a subscription is existing, so you can't subscription new plan`,
  SUBSCRIPTION_NOT_FOUND: `Subscription not found`,
  SUBSCRIPTION_BEING_ACTIVE: `You can't resume a subscription active`,
  HAVE_NOT_SUBSCRIPTION: `Subscription new plan to invite practitioner`,
  OVER_AMOUNT_PLAN: `You can't invite over amount of subscription`,
  PROFILE_REALLOCATE_NOT_FOUND: 'This profile you want to reallocate is not exist',
  PROFILE_REALLOCATE_NOT_ACTIVE: 'This profile you want to reallocate is not active',
  REACTIVATE_PROFILE_STATUS_NOT_VALID: 'Can not reactive this profile due to profile status error',
  ACTIVE_PROFILE_EXCEED: 'The number of active profiles is exceeded',
  RESEND_INVITATION_FAIL: 'Only resend invitation for Pending profile',
  REVOKE_INVITATION_FAIL: 'Only revoke invitation for Pending profile',
  CAN_NOT_CHANGE_HOMEWORK_IN_TOPIC: 'Can not change these homeworks in this topic',
  CARD_EXISTED: `This card is created`,
  SUBSCRIPTION_CANCEL_NOT_EXPIRED: `Current subscription has been canceled`,
  ATTACHMENT_NOT_FOUND: `Attachment not found`,
  CLIENT_NOT_DEPEND_ON: `This client is not available for you`,
  ROOM_NOT_FOUND: `Room not found`,
  MESSAGE_NOT_FOUND: `Message not found`,
  NOT_EXIST_IN_ROOM: `You does't exist in this conversation`,
  RESEND_CLIENT_INVITATION_FAIL: 'Only resend invitation for Pending client',
  REVOKE_CLIENT_INVITATION_FAIL: 'Only revoke invitation for Pending client',
  CLIENT_NOT_DEPEND_ON_PRACTITIONER: `You are not available for this practitioner`,
  CLINIC_NOT_FOUND: 'Clinic not found',
  REACTIVE_CLIENT_FAIL: 'Reactive client fail due to status error',
  QUOTE_NOT_FOUND: 'Quote not found',
  FILE_NOT_FOUND: 'File not found',
  DEVICE_TOKEN_NOT_FOUND: 'Token not found',
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  FILE_NAME_EXISTED: 'File name existed',
  CAN_NOT_SEND_MESSAGE_TO_INACTIVE_RECEIVER: 'Can not send message to inactive receiver',
  RESET_TOKEN_INVALID: 'Reset token invalid',
  RESET_TOKEN_EXPIRED: 'Reset token expired',
  RESET_TOKEN_USED: 'Reset token used',
  PSYCHOEDUCATION_TOPIC_NOT_FOUND: 'Psychoeducation topic not found',
  PSYCHOEDUCATION_NOT_FOUND: 'Psychoeducation not found',
  INVALID_OLD_PASSWORD: 'The current password is incorrect',
  ACCOUNT_NOT_FOUND: 'Account not found',
  FOLDER_NOT_FOUND: 'Folder not found',
  ONLY_DEVICE_LOGIN: `Your account is already logged in on another device, please login again`,
  PASSWORD_INVALID: `The email couldn’t be used as password. Please create another password.`,
  OTP_INVALID: `OTP is not correct. Try again`,
  INVITATION_REVOKED: `Invitation of practitioner is revoked`,
  PRACTITIONER_TYPE_NOT_FOUND: 'Practitioner type not found',
  NO_PLAN_EXISTED: `There is no plan to continue. Please subscription new plan`,
  ACCOUNT_DEACTIVATED: `Your account is deactivated`,
  NOT_ALLOW_DELETE_ACCOUNT: 'Not allow delete account',
  CAN_NOT_DELETE_HOMEWORK_TOPIC: 'Cannot delete topic that contains assigned homework',
  CAN_NOT_DELETE_HOMEWORK: 'Cannot delete assigned homework',
  HOMEWORK_DELETED_BY_ADMIN: 'This homework is deleted by admin, please assign another',
  HOMEWORK_NOT_FOUND: 'This homework has been deleted by admin',
};
