export enum ConfigurationsEnum {
  HOST = 'HOST',
  PORT = 'PORT',

  JWT_SECRET = 'JWT_SECRET',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',

  ADMIN_EMAIL = 'ADMIN_EMAIL',
  ADMIN_EMAIL_PASSWORD = 'ADMIN_EMAIL_PASSWORD',

  APP_URL = 'APP_URL',
  JWT_EXPIRE_IN = 'JWT_EXPIRE_IN',

  S3_REGION = 'S3_REGION',
  S3_BUCKET_NAME = 'S3_BUCKET_NAME',
  S3_ACCESS_KEY = 'S3_ACCESS_KEY',
  S3_SECRET_KEY = 'S3_SECRET_KEY',
  S3_MEDIA_PREFIX = 'S3_MEDIA_PREFIX',

  LOG_DIR = 'LOG_DIR',
  DEFAULT_TIMEZONE = 'DEFAULT_TIMEZONE',

  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  OTP_EXPIRE = 'OTP_EXPIRE',

  EMAIL_SUPPORT = 'EMAIL_SUPPORT',
  ALLOW_DELETE_ACCOUNT = 'ALLOW_DELETE_ACCOUNT',
  TIME_CLIENT_ACTIVE_AFTER_DISCHARGE = 'TIME_CLIENT_ACTIVE_AFTER_DISCHARGE',
}
